<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Version>1.2.0</Version>
    <GameManaged Condition="'$(GameManaged)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Timberborn\Timberborn_Data\Managed</GameManaged>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="$(GameManaged)\Timberborn.*.dll" Private="false" />
    <Reference Include="$(GameManaged)\UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="$(GameManaged)\Bindito.Core.dll" Private="false" />
    <Reference Include="$(GameManaged)\Newtonsoft.Json.dll" Private="false" />
  </ItemGroup>
</Project>
